# Publish all joint states -----------------------------------
car_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint velocity controllers ---------------------------------
front_car_motor_r_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_r_wheel_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

front_car_motor_l_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_l_wheel_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

back_car_motor_r_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_r_wheel_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

back_car_motor_l_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_l_wheel_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

#/gazebo_ros_control/pid_gains:
#right_wheel: {p: 1.0, i: 0, d: 0.01}
#left_wheel: {p: 1.0, i: 0, d: 0.01}
